
import {createHmac, timingSafeEqual} from 'node:crypto'

import {CONFIRM_SECRET} from './config.js'
import {book_db, escape_html} from './common.js'
import {get_lulu_access_token, submit_order, validate_order} from './lulu.js'
import {PRODUCTS, is_manual_fulfilment} from './products.js'
import type {ProductId} from './products.js'
import type {Order} from './types.js'


// Signature proving a confirm link was generated by us for this particular order
export function sign_order_id(order_id:string):string{
    return createHmac('sha256', CONFIRM_SECRET.value()).update(order_id).digest('hex')
}


// Compare a given signature against the expected one, without leaking timing information
function signature_valid(order_id:string, given:string):boolean{
    const expected_buffer = Buffer.from(sign_order_id(order_id))
    const given_buffer = Buffer.from(given)
    if (expected_buffer.length !== given_buffer.length){
        return false
    }
    return timingSafeEqual(expected_buffer, given_buffer)
}


// Load an order, checking the signature first (returns a string if it can't be actioned)
async function get_confirmable_order(order_id:string, signature:string)
        :Promise<string|{order:Order}>{

    if (!order_id || !signature_valid(order_id, signature)){
        return "This link is not valid"
    }

    const order = await book_db.collection('book_orders').doc(order_id).get()
    if (!order.exists){
        return "This order no longer exists"
    }

    const order_data = order.data() as Order
    if (order_data.state.status !== 'new'){
        return `This order has already been actioned (${order_data.state.status})`
    }

    return {order: order_data}
}


// Build the page shown when someone opens a confirm link
// SECURITY This is a GET, so it must never change anything
export async function show_confirm_page(order_id:string, signature:string):Promise<string>{

    const result = await get_confirmable_order(order_id, signature)
    if (typeof result === 'string'){
        return page_html("Order", `<h1>Order</h1><p>${escape_html(result)}</p>`)
    }
    const order = result.order

    const books = Object.entries(order.books)
        .map(([id, options]) => `${PRODUCTS[id as ProductId].title} &times;${options.quantity}`)
        .join('<br>')

    const manual = is_manual_fulfilment(order.address.country)
    const method = manual ? "sent by hand (Amazon)" : "printed and posted by Lulu"

    const address = [
        order.name,
        order.address.street1,
        order.address.street2,
        `${order.address.city} ${order.address.state} ${order.address.postcode}`,
        order.address.country,
        order.address.phone,
    ].filter(line => line.trim()).map(line => escape_html(line)).join('<br>')

    return page_html("Confirm order", `
        <h1>Confirm order</h1>
        <table>
            <tr><th>Books</th><td>${books}</td></tr>
            <tr><th>Deliver to</th><td>${address}</td></tr>
            <tr><th>Email</th><td>${escape_html(order.email)}</td></tr>
            <tr><th>Lulu cost</th><td>${order.state.cost} ${escape_html(order.state.currency)}</td></tr>
            <tr><th>Method</th><td>${method}</td></tr>
        </table>
        <form method="post">
            <input type="hidden" name="id" value="${escape_html(order_id)}">
            <input type="hidden" name="sig" value="${escape_html(signature)}">
            <button type="submit" name="action" value="confirm" class="confirm">Confirm</button>
            <button type="submit" name="action" value="cancel" class="cancel">Cancel order</button>
        </form>
    `)
}


// Act on a confirmation (returns HTML to show the person who clicked)
export async function do_confirm(order_id:string, signature:string, action:string)
        :Promise<string>{

    const result = await get_confirmable_order(order_id, signature)
    if (typeof result === 'string'){
        return page_html("Order", `<h1>Order</h1><p>${escape_html(result)}</p>`)
    }
    const order = result.order
    const order_ref = book_db.collection('book_orders').doc(order_id)
    const name = escape_html(order.name)

    // Declining an order records it, rather than leaving it as new forever
    if (action === 'cancel'){
        await order_ref.update({
            'state.status': 'cancelled',
            'state.confirmed_at': new Date(),
        })
        return page_html("Order cancelled",
            `<h1>Order cancelled</h1><p>The order for ${name} has been cancelled.</p>`)
    }

    if (action !== 'confirm'){
        return page_html("Order", `<h1>Order</h1><p>Unknown action.</p>`)
    }

    // Countries we have an Amazon listing for are fulfilled by hand
    if (is_manual_fulfilment(order.address.country)){
        await order_ref.update({
            'state.status': 'sent_manually',
            'state.confirmed_at': new Date(),
        })
        return page_html("Order confirmed",
            `<h1>Order confirmed</h1><p>The order for ${name} is marked as sent by hand.
            Remember to actually place it on Amazon.</p>`)
    }

    // Everything else goes to Lulu for print on demand
    const access_token = await get_lulu_access_token()
    if (!access_token){
        return page_html("Error", `<h1>Error</h1><p>Couldn't connect to Lulu, please try again.</p>`)
    }

    // Double check the order is still valid and not too expensive
    const validation = await validate_order(access_token, order)
    if (typeof validation === 'string'){
        return page_html("Error", `<h1>Error</h1><p>${escape_html(validation)}</p>`)
    }

    const lulu_id = await submit_order(access_token, order_id, order)
    if (typeof lulu_id === 'string'){
        return page_html("Error", `<h1>Error</h1><pre>${escape_html(lulu_id)}</pre>`)
    }

    // NOTE cost and shipping dates are not available straight away (at least in sandbox)
    await order_ref.update({
        'state.status': 'sent_lulu',
        'state.confirmed_at': new Date(),
        'state.lulu_id': lulu_id,
    })

    return page_html("Order confirmed",
        `<h1>Order confirmed</h1><p>The order for ${name} has been sent to Lulu.</p>`)
}


// A page saying a single thing, for outcomes and errors
export function render_message_page(title:string, message:string):string{
    return page_html(title, `<h1>${escape_html(title)}</h1><p>${escape_html(message)}</p>`)
}


// Wrap body content in a minimal self-contained page
function page_html(title:string, body:string):string{
    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>${escape_html(title)}</title>
<style>
body {font-family: system-ui, sans-serif; max-width: 40rem; margin: 3rem auto; padding: 0 1rem;
    line-height: 1.5; color: #222; background: #fff}
table {border-collapse: collapse; margin: 2rem 0}
th {text-align: left; vertical-align: top; padding: 0.5rem 1.5rem 0.5rem 0; white-space: nowrap}
td {padding: 0.5rem 0}
button {font-size: 1rem; padding: 0.75rem 1.5rem; margin-right: 1rem; border: none;
    border-radius: 0.4rem; cursor: pointer; color: #fff}
.confirm {background: #276749}
.cancel {background: #9b2c2c}
pre {white-space: pre-wrap; background: #f4f4f4; padding: 1rem; border-radius: 0.4rem}
</style>
</head>
<body>
${body}
</body>
</html>`
}
